Release 1.92
microsoft/vsts-extension-retrospectives pull request #632
Opened 2024-01-18 03:54 UTC by JStuve

# Pull Request

Relevant Issue(s): Release changes from the past several months

## Description

Release updates from over the past few months.

## Bug or Feature?

- [ ] Bug fix
- [X] New feature

## Fundamentals

- [ ] I have read the [**CONTRIBUTING**](https://github.com/microsoft/vsts-extension-retrospectives/blob/main/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] I have updated any relevant documentation accordingly.
- [ ] I have included an update blurb (50 words or less) at the top of `CHANGELOG.md`,
    to be included with the next release.
  - [ ] I have included a link to this PR in that blurb.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Accessibility

- [ ] I have tested my changes on both light and dark themes.
- [ ] I have tested my changes on both mobile and desktop views, when needed.
- [ ] I have included image descriptions and aria-labels where I can.

## Screenshots and Logs

2024-01-18 03:55 UTC, JStuve commented
@polatengin Ready to release the changes. We will most likely need an new access token for the CD pipeline.

2024-01-18 04:35 UTC, polatengin requested changes
I left a minor comment

2024-01-18 04:35 UTC, polatengin commented on RetrospectiveExtension.Frontend/vss-extension-prod.json
> +  "version": "1.92.0",
shouldn't it be `1.92.1`?

2024-01-19 00:13 UTC, JStuve commented on RetrospectiveExtension.Frontend/vss-extension-prod.json
> +  "version": "1.92.0",
Yup, thanks, increased the number

2024-01-25 20:20 UTC, polatengin approved these changes
👍

2024-01-25 20:20 UTC, merged